### ISSUE TITLE
使用文档

### ISSUE THREAD

**Issue by Jiahe-Sun** [wz-dazhi/Yomiao#1]
您好，请问该程序如何使用呢？需要配置接口吗？期待您的解答

**Comment by wz-dazhi** [comment]
这个是监控约苗到货的通知脚本, 具体配置文件是config.ini里. 需要通过抓包的方式将约苗接口的token配置到config.ini里, 还有你需要监控二价的还是四价的 config.ini里也都有注释, 可根据要监控的具体的疫苗进行配置(可配置多个, 用逗号隔开). 到货的疫苗会通过pushplus进行推送到微信, 具体的监控方式需要你在脚本里写死循环, 或者使用Linux crontab定时任务的方式进行执行. 如果还有不明白的可以添加QQ: 742820195

**Comment by Jiahe-Sun** [comment]
感谢你的分享！




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年9月1日(星期三) 上午9:52
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [wz-dazhi/Yomiao] 使用文档 (#1)





 
这个是监控约苗到货的通知脚本, 具体配置文件是config.ini里. 需要通过抓包的方式将约苗接口的token配置到config.ini里, 还有你需要监控二价的还是四价的 config.ini里也都有注释, 可根据要监控的具体的疫苗进行配置(可配置多个, 用逗号隔开). 到货的疫苗会通过pushplus进行推送到微信, 具体的监控方式需要你在脚本里写死循环, 或者使用Linux crontab定时任务的方式进行执行. 如果还有不明白的可以添加QQ: 742820195
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by wz-dazhi** [comment]
不客气
